import numpy as np

def enumerateOrientations():
    # Function to enumerate all possible right angle orientations of a component

    coordsA = np.array([1,2,3])
    coordsB = np.array([2,-1,3])
    flipMult = np.array([-1,-1,1])
    matLine = np.array([1,0,0])

    allCoords = []
    allMats = []
    for iA in range(len(coordsA)):
        newCoordsA = np.roll(coordsA,iA)
        allCoords.append(newCoordsA)
        for jA in range(len(flipMult)):
            flipMultTemp = np.roll(flipMult,jA)
            newFlipCoordsA = np.multiply(newCoordsA,flipMultTemp)
            allCoords.append(newFlipCoordsA)
    
    for iB in range(len(coordsB)):
        newCoordsB = np.roll(coordsB,iB)
        allCoords.append(newCoordsB)
        for jB in range(len(flipMult)):
            flipMultTemp = np.roll(flipMult,jB)
            newFlipCoordsB = np.multiply(newCoordsB,flipMultTemp)
            allCoords.append(newFlipCoordsB)
    
    for iM in range(len(allCoords)):
        newMat = np.array([matLine,matLine,matLine])
        for jM in range(len(allCoords[iM])):
            newMat[jM] = np.roll(newMat[jM],abs(allCoords[iM][jM])-1)
            newMat[jM] = newMat[jM]*np.sign(allCoords[iM][jM])
        allMats.append(newMat)
    
    return allCoords, allMats

def getOrientation(orientationChoice):
    # function to get the transformation matrix for a given orientation choice

    coordsA = np.array([1,2,3])
    coordsB = np.array([2,-1,3])
    flipMult = np.array([-1,-1,1])
    matBase = np.array([[1,0,0],[1,0,0],[1,0,0]])

    # choose between even and odd orientations
    if orientationChoice >= 0 and orientationChoice <= 11:
        coordsUsed = coordsA
    elif orientationChoice >= 12 and orientationChoice <= 23:
        coordsUsed = coordsB

    rollNum = np.floor_divide(orientationChoice,4)
    coord = np.roll(coordsUsed,rollNum)
    if np.mod(orientationChoice,4) != 0:
        rollNumFlip = np.mod(orientationChoice,4)
        newFlipMult = np.roll(flipMult,rollNumFlip)
        coord = np.multiply(coord,newFlipMult)

    # create the transformation matrix
    transMat = matBase
    for i in range(3):
        transMatPos = np.roll(matBase[i],abs(coord[i])-1)
        transMat[i] = transMatPos*np.sign(coord[i])

    return transMat

def Euler2DCM(eulerAngles=[0,0,0]):
    """
    Function to get the DCM from the euler angles generated by the
    varous configuration algorithms

    Used the 3-2-1 eular angle convention (psi-theta-phi)

    inputs are a list of the three euler angles (phi,theta,psi) in radians
    output is a dcm of the rotation
    """
    phi = eulerAngles[0]
    theta = eulerAngles[1]
    psi = eulerAngles[2]

    R1phi = np.array([[1,0,0],[0,np.cos(phi),-np.sin(phi)],[0,np.sin(phi),np.cos(phi)]])
    R2theta = np.array([[np.cos(theta),0,np.sin(theta)],[0,1,0],[-np.sin(theta),0,np.cos(theta)]])
    R3psi = np.array([[np.cos(psi),-np.sin(psi),0],[np.sin(psi),np.cos(psi),0],[0,0,1]])

    DCM321 = np.matmul(R3psi,np.matmul(R2theta,R1phi))

    return DCM321

def faceAndRot2DCM(faceChoice=0, rot=0):
    """
    Function to get the DCM of the component relative to the panel from the face and rotation
    facechoice=0 means the z axis of the component is aligned with the normal of the panel face
    1 mean y
    2 means x
    3 means -z
    4 means -y
    5 means -x

    input is facechoice 0 through 5 and rotation about axis normal to panel in radians
    output is a DCM of the component relative to the panel
    """

    if faceChoice == 0:
        compDCM = np.array([[1,0,0],[0,1,0],[0,0,1]])
    elif faceChoice == 1:
        compDCM = np.array([[0,0,1],[1,0,0],[0,1,0]])
    elif faceChoice == 2:
        compDCM = np.array([[0,1,0],[0,0,1],[1,0,0]])
    elif faceChoice == 3:
        compDCM = np.array([[0,1,0],[1,0,0],[0,0,-1]])
    elif faceChoice == 4:
        compDCM = np.array([[1,0,0],[0,0,1],[0,-1,0]])
    elif faceChoice == 5:
        compDCM = np.array([[0,0,1],[0,1,0],[-1,0,0]])

    rotDCM = np.array([[np.cos(rot),np.sin(rot),0],[-np.sin(rot),np.cos(rot),0],[0,0,1]])

    # print("Face DCM: ", compDCM)
    # print("Rot DCM: ", rotDCM)
    # print("\n\nFace Choice: ", faceChoice)
    # print("Rotation: ", rot)

    combinedDCM = np.matmul(rotDCM,compDCM)

    # print("Combined DCM: ", combinedDCM)

    return combinedDCM

def align_cuboid_with_plane(cuboid_dcm, plane_dcm):

    # print("\nComponent DCM: ", cuboid_dcm)
    # print("Panel DCM: ", plane_dcm)
    # totalDCM = np.matmul(cuboid_dcm, plane_dcm)
    totalDCM2 = np.matmul(plane_dcm, cuboid_dcm)
    # totalDCM3 = np.matmul(np.transpose(cuboid_dcm), np.transpose(plane_dcm))
    # totalDCM4 = np.matmul(np.transpose(plane_dcm), np.transpose(cuboid_dcm))
    # print("Total DCM 1: ", totalDCM)
    # print("Total DCM 2: ", totalDCM2)
    # print("Total DCM 3: ", totalDCM3)
    # print("Total DCM 4: ", totalDCM4)
    return totalDCM2

    # """
    # Aligns the cuboid's local z-axis with the normal of the plane using rotation matrices.

    # Parameters:
    # - cuboid_dcm: (3,3) ndarray, DCM of the cuboid in the inertial frame.
    # - plane_dcm: (3,3) ndarray, DCM of the plane in the inertial frame.

    # Returns:
    # - new_cuboid_dcm: (3,3) ndarray, updated DCM of the cuboid aligned with the plane.
    # """
    # # Extract the normal vector of the plane (third column of the plane's DCM)
    # normal = plane_dcm[:, 2]
    
    # # Initial cuboid z-axis in the inertial frame
    # z_cuboid = np.array([0, 0, 1])

    # # Compute the axis of rotation (cross product)
    # axis = np.cross(z_cuboid, normal)
    
    # # Compute the rotation angle
    # cos_theta = np.dot(z_cuboid, normal)
    # theta = np.arccos(np.clip(cos_theta, -1.0, 1.0))  # Clip for numerical stability

    # # If already aligned, return the original cuboid DCM
    # if np.isclose(theta, 0):
    #     return cuboid_dcm

    # # Compute the skew-symmetric matrix for Rodrigues' rotation formula
    # axis_norm = np.linalg.norm(axis)
    # if axis_norm < 1e-6:  # Avoid division by zero
    #     return cuboid_dcm

    # axis = axis / axis_norm  # Normalize rotation axis
    # K = np.array([
    #     [0, -axis[2], axis[1]],
    #     [axis[2], 0, -axis[0]],
    #     [-axis[1], axis[0], 0]
    # ])

    # # Compute the rotation matrix using Rodrigues' formula
    # R = np.eye(3) + np.sin(theta) * K + (1 - np.cos(theta)) * np.dot(K, K)

    # # Compute the new cuboid DCM by applying the rotation
    # new_cuboid_dcm = R @ cuboid_dcm

    # return new_cuboid_dcm
        
def getCube(dimensions,location,orientation):
        # Function to transform cube dimensions and location into a form that plot_surface can plot
        phi = np.arange(1,10,2)*np.pi/4
        Phi, Theta = np.meshgrid(phi, phi)

        xBody = np.cos(Phi)*np.sin(Theta) * dimensions[0]
        yBody = np.sin(Phi)*np.sin(Theta) * dimensions[1]
        zBody = np.cos(Theta)/np.sqrt(2) * dimensions[2]

        bodyCoords = np.array([xBody,yBody,zBody])
        bodyCoordsNew = bodyCoords.reshape(3,-1)
        coords = np.matmul(orientation,bodyCoordsNew)
        coords = coords.reshape(3,5,5)
        location = np.array(location)
        coords = coords + location[:, np.newaxis, np.newaxis]

        x,y,z = coords

        return x,y,z